version: '3'

services: 
    anken_server:
        image: python:3
        container_name: anken_server
        working_dir: /src
        environment:
            - http_proxy=${http_proxy}
            - https_proxy=${https_proxy}
            - HTTP_PROXY=${HTTP_PROXY}
            - HTTPS_PROXY=${HTTPS_PROXY}
        volumes:
            - ./src:/src
#           - path/to/AnkenSugoroku/web/resources:/src/static/
            - anken_data:/var/ankenSugoroku/
        ports:
            - "8080:5000"
        command: ["bash", "startup.sh"]

volumes:
    anken_data:
        driver: local
